name: flutter_wordpress_app
description: "Flutter news app for wordpress platform"
version: 2.0.0+5

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  http: ^1.2.2
  html: ^0.15.4
  flutter_html: ^2.2.1
  dio: ^5.7.0
  intl: ^0.20.1
  share_plus: ^6.3.4
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  shared_preferences: ^2.3.4
  flutter_widget_from_html: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/launcher_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/no-internet.png
    - assets/play-button.png
    - assets/boxed/fashion.png
    - assets/boxed/health.png
    - assets/boxed/lifestyle.png
    - assets/boxed/music.png
    - assets/boxed/photography.png
    - assets/boxed/recipies.png
    - assets/boxed/sport.png
    - assets/boxed/travel.png
    - assets/boxed/world.png
    - assets/more/favourite.png
    - assets/more/contact.png
    - assets/more/share.png
    - assets/more/notification.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Bold.ttf

    - family: Soleil
      fonts:
        - asset: fonts/Soleil/Soleil-Bold.otf
        - asset: fonts/Soleil/Soleil-Regular.otf
